//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public Block()
        {
            this.Fields = new HashSet<Field>();
        }
    
        public int BlockId { get; set; }
        public int BlockTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Area { get; set; }
        public int LeaseTypeId { get; set; }
        public Nullable<long> YearOfAward { get; set; }
        public long CompanyId { get; set; }
    
        public virtual BlockType BlockType { get; set; }
        public virtual Company Company { get; set; }
        public virtual LeaseType LeaseType { get; set; }
        public virtual ICollection<Field> Fields { get; set; }
    }
}
