//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.EquipmentUsageHistories = new HashSet<EquipmentUsageHistory>();
            this.Fields = new HashSet<Field>();
            this.People = new HashSet<Person>();
            this.Projects = new HashSet<Project>();
            this.IncidentHistories = new HashSet<IncidentHistory>();
            this.Blocks = new HashSet<Block>();
        }
    
        public long CompanyId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string RCNumber { get; set; }
        public string CanonialName { get; set; }
    
        public virtual ICollection<EquipmentUsageHistory> EquipmentUsageHistories { get; set; }
        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<IncidentHistory> IncidentHistories { get; set; }
        public virtual ICollection<Block> Blocks { get; set; }
    }
}
