//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DPRDataMigrationEngineDBEntities : DbContext
    {
        public DPRDataMigrationEngineDBEntities()
            : base("name=DPRDataMigrationEngineDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlockType> BlockTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<EquipmentUsageHistory> EquipmentUsageHistories { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<IncidentType> IncidentTypes { get; set; }
        public virtual DbSet<LeaseType> LeaseTypes { get; set; }
        public virtual DbSet<MilestoneStatu> MilestoneStatus { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProjectMileStone> ProjectMileStones { get; set; }
        public virtual DbSet<ProjectRep> ProjectReps { get; set; }
        public virtual DbSet<ProjectType> ProjectTypes { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<Sys_Param> Sys_Param { get; set; }
        public virtual DbSet<Terrain> Terrains { get; set; }
        public virtual DbSet<WellClass> WellClasses { get; set; }
        public virtual DbSet<WellClassification> WellClassifications { get; set; }
        public virtual DbSet<WellCompletion> WellCompletions { get; set; }
        public virtual DbSet<WellCompletionInterval> WellCompletionIntervals { get; set; }
        public virtual DbSet<WellCompletionType> WellCompletionTypes { get; set; }
        public virtual DbSet<WellType> WellTypes { get; set; }
        public virtual DbSet<WellWorkover> WellWorkovers { get; set; }
        public virtual DbSet<WellWorkOverReason> WellWorkOverReasons { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
        public virtual DbSet<Production> Productions { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Well> Wells { get; set; }
        public virtual DbSet<IncidentHistory> IncidentHistories { get; set; }
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
    }
}
