//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentUsageHistory
    {
        public int EquipmentUsageHistoryId { get; set; }
        public long CompanyId { get; set; }
        public int EquipmentId { get; set; }
        public int WellId { get; set; }
        public System.DateTime DateUsed { get; set; }
        public int WellCompletionId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual WellCompletion WellCompletion { get; set; }
        public virtual Well Well { get; set; }
    }
}
