//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.EquipmentUsageHistories = new HashSet<EquipmentUsageHistory>();
            this.WellCompletions = new HashSet<WellCompletion>();
            this.WellWorkovers = new HashSet<WellWorkover>();
        }
    
        public int EquipmentId { get; set; }
        public string Name { get; set; }
        public int EquipmentTypeId { get; set; }
        public bool LicenseStatus { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual ICollection<EquipmentUsageHistory> EquipmentUsageHistories { get; set; }
        public virtual ICollection<WellCompletion> WellCompletions { get; set; }
        public virtual ICollection<WellWorkover> WellWorkovers { get; set; }
    }
}
