//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Productions = new HashSet<Production>();
            this.Wells = new HashSet<Well>();
        }
    
        public int FieldId { get; set; }
        public long CompanyId { get; set; }
        public int ZoneId { get; set; }
        public int TerrainId { get; set; }
        public string Name { get; set; }
        public Nullable<double> TechnicalAllowable { get; set; }
        public int BlockId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Terrain Terrain { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ICollection<Production> Productions { get; set; }
        public virtual ICollection<Well> Wells { get; set; }
        public virtual Block Block { get; set; }
    }
}
