//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldQuery
    {
        public long FieldQueryId { get; set; }
        public Nullable<int> TerrainId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string FieldQueryName { get; set; }
        public Nullable<int> BlockId { get; set; }
    }
}
