//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentHistory
    {
        public int IncidentHistoryId { get; set; }
        public long CompanyId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int IncidentTypeId { get; set; }
        public System.DateTime IncidentDate { get; set; }
        public string Location { get; set; }
        public string ReportedBy { get; set; }
        public string CraetedBy { get; set; }
        public byte[] TimeCreated { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual IncidentType IncidentType { get; set; }
    }
}
