//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.ProjectReps = new HashSet<ProjectRep>();
        }
    
        public long PersonId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public long CompanyId { get; set; }
        public string Designation { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<ProjectRep> ProjectReps { get; set; }
    }
}
