//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int ProductionId { get; set; }
        public int ProductId { get; set; }
        public int FieldId { get; set; }
        public string Quantity { get; set; }
        public int Month { get; set; }
        public long Year { get; set; }
        public string Remark { get; set; }
        public string APIGravity { get; set; }
        public string CreatedBy { get; set; }
        public byte[] TimeCreated { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Product Product { get; set; }
    }
}
