//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectMileStones = new HashSet<ProjectMileStone>();
            this.ProjectReps = new HashSet<ProjectRep>();
        }
    
        public long ProjectId { get; set; }
        public int TerrainId { get; set; }
        public int SectorId { get; set; }
        public long CompanyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ProjectTypeId { get; set; }
        public int Duration { get; set; }
        public double Cost { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string ProjectObjectives { get; set; }
        public int CompletionStatus { get; set; }
        public string CreatedBy { get; set; }
        public byte[] TimeCreated { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Terrain Terrain { get; set; }
        public virtual ICollection<ProjectMileStone> ProjectMileStones { get; set; }
        public virtual ICollection<ProjectRep> ProjectReps { get; set; }
    }
}
