//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMileStone
    {
        public ProjectMileStone()
        {
            this.ProjectMileStone1 = new HashSet<ProjectMileStone>();
        }
    
        public long ProjectMileStoneId { get; set; }
        public long ParentId { get; set; }
        public long ProjectId { get; set; }
        public string Title { get; set; }
        public System.DateTime DateDue { get; set; }
        public string LastUpdated { get; set; }
        public int MileStoneStatusId { get; set; }
        public string Description { get; set; }
    
        public virtual MilestoneStatu MilestoneStatu { get; set; }
        public virtual ICollection<ProjectMileStone> ProjectMileStone1 { get; set; }
        public virtual ProjectMileStone ProjectMileStone2 { get; set; }
        public virtual Project Project { get; set; }
    }
}
