//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRep
    {
        public int ProjectRepId { get; set; }
        public long ProjectId { get; set; }
        public long PersonId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Project Project { get; set; }
    }
}
