//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public long ProviderId { get; set; }
        public string ProviderSecrete { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Name { get; set; }
        public long ProviderKey { get; set; }
        public int AllowedGrant { get; set; }
        public string RedirectUrl { get; set; }
        public byte[] ProviderLogo { get; set; }
    }
}
