//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Param
    {
        public int Sys_ParamId { get; set; }
        public string ServerName { get; set; }
        public string ServerLoginName { get; set; }
        public string ServerLoginPassword { get; set; }
        public string DBName { get; set; }
    }
}
