//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terrain
    {
        public Terrain()
        {
            this.Fields = new HashSet<Field>();
            this.Projects = new HashSet<Project>();
        }
    
        public int TerrainId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
