//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellCompletion
    {
        public WellCompletion()
        {
            this.EquipmentUsageHistories = new HashSet<EquipmentUsageHistory>();
            this.WellCompletionIntervals = new HashSet<WellCompletionInterval>();
        }
    
        public int WellCompletionId { get; set; }
        public int WellId { get; set; }
        public int EquipmentId { get; set; }
        public int WellCompletionTypeId { get; set; }
        public bool IsInitial { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string CreatedBy { get; set; }
        public byte[] TimeCreated { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ICollection<EquipmentUsageHistory> EquipmentUsageHistories { get; set; }
        public virtual WellCompletionType WellCompletionType { get; set; }
        public virtual ICollection<WellCompletionInterval> WellCompletionIntervals { get; set; }
        public virtual Well Well { get; set; }
    }
}
