//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellCompletionInterval
    {
        public int WellCompletionIntervalId { get; set; }
        public int WellCompletionId { get; set; }
        public double LowerInterval { get; set; }
        public double UpperInterval { get; set; }
        public string DateCompleted { get; set; }
        public string LastUpdatedTime { get; set; }
    
        public virtual WellCompletion WellCompletion { get; set; }
    }
}
