//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Well
    {
        public Well()
        {
            this.EquipmentUsageHistories = new HashSet<EquipmentUsageHistory>();
            this.WellClassifications = new HashSet<WellClassification>();
            this.WellCompletions = new HashSet<WellCompletion>();
            this.WellWorkovers = new HashSet<WellWorkover>();
        }
    
        public int WellId { get; set; }
        public int WellTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<double> TechnicalAllowable { get; set; }
        public Nullable<double> TotalDept { get; set; }
        public Nullable<System.DateTime> SpudDate { get; set; }
        public string Remarks { get; set; }
        public int FieldId { get; set; }
    
        public virtual ICollection<EquipmentUsageHistory> EquipmentUsageHistories { get; set; }
        public virtual Field Field { get; set; }
        public virtual WellType WellType { get; set; }
        public virtual ICollection<WellClassification> WellClassifications { get; set; }
        public virtual ICollection<WellCompletion> WellCompletions { get; set; }
        public virtual ICollection<WellWorkover> WellWorkovers { get; set; }
    }
}
