//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellCompletionQuery
    {
        public long WellCompletionQueryId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> WellId { get; set; }
        public Nullable<int> WellTypeId { get; set; }
        public Nullable<int> TerrainId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> CompletionTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public string WellCompletionQueryName { get; set; }
        public Nullable<int> WellClassId { get; set; }
    }
}
