//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellClassification
    {
        public int WellClassificationId { get; set; }
        public int WellId { get; set; }
        public int WellClassId { get; set; }
    
        public virtual WellClass WellClass { get; set; }
        public virtual Well Well { get; set; }
    }
}
