//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellQuery
    {
        public long WellQueryId { get; set; }
        public Nullable<int> WellTypeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public int WellClassId { get; set; }
        public Nullable<int> TerrainId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string WellQueryName { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
