//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellWorkOverReason
    {
        public WellWorkOverReason()
        {
            this.WellWorkovers = new HashSet<WellWorkover>();
        }
    
        public int WellWorkOverReasonId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<WellWorkover> WellWorkovers { get; set; }
    }
}
