//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellCompletionType
    {
        public WellCompletionType()
        {
            this.WellCompletions = new HashSet<WellCompletion>();
        }
    
        public int WellCompletionTypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<WellCompletion> WellCompletions { get; set; }
    }
}
