//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellType
    {
        public WellType()
        {
            this.Wells = new HashSet<Well>();
        }
    
        public int WellTypeId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Well> Wells { get; set; }
    }
}
