//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_DataMigrationEngine.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public Zone()
        {
            this.Fields = new HashSet<Field>();
        }
    
        public int ZoneId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Field> Fields { get; set; }
    }
}
